version: '3'

services:
  nginx:
    image: nginx
    container_name: tmp_nginx
    ports:
      - "80:80"
      - "8001:8001"
      - "8002:8002"
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/template.conf:/etc/nginx/conf.d/template.conf
  php:
    build:
      context: ./docker/php
    container_name: tmp_php
    volumes:
      - ./:/var/www/html
    environment:
      - DB_NAME=template
      - DB_USER=user
      - DB_PASSWORD=secret
  db:
    image: mysql
    container_name: tmp_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=template
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    volumes:
      - ./docker/database:/var/lib/mysql
  adminer:
    image: adminer
    container_name: tmp_adminer
    restart: always
    ports:
      - "8081:8080"